# Project: FinalProject
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = pong.o $(RES)
LINKOBJ  = pong.o $(RES)
LIBS =  -L"C:/Users/Jesus/OneDrive/Documents/CS 2120 - Computer Graphics and Game Construction/Dev_C++_is_a_portable_app/Dev_C++_is_a_portable_app/Dev-CppPortable/App/devcpp/lib" -mwindows -lalleg 
INCS =  -I"C:/Users/Jesus/OneDrive/Documents/CS 2120 - Computer Graphics and Game Construction/Dev_C++_is_a_portable_app/Dev_C++_is_a_portable_app/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/Jesus/OneDrive/Documents/CS 2120 - Computer Graphics and Game Construction/Dev_C++_is_a_portable_app/Dev_C++_is_a_portable_app/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Jesus/OneDrive/Documents/CS 2120 - Computer Graphics and Game Construction/Dev_C++_is_a_portable_app/Dev_C++_is_a_portable_app/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/Jesus/OneDrive/Documents/CS 2120 - Computer Graphics and Game Construction/Dev_C++_is_a_portable_app/Dev_C++_is_a_portable_app/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Jesus/OneDrive/Documents/CS 2120 - Computer Graphics and Game Construction/Dev_C++_is_a_portable_app/Dev_C++_is_a_portable_app/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/Jesus/OneDrive/Documents/CS 2120 - Computer Graphics and Game Construction/Dev_C++_is_a_portable_app/Dev_C++_is_a_portable_app/Dev-CppPortable/App/devcpp/include" 
BIN  = FinalProject.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before FinalProject.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "FinalProject.exe" $(LIBS)

pong.o: pong.cpp
	$(CPP) -c pong.cpp -o pong.o $(CXXFLAGS)
